#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Zsh theme
autoload -Uz promptinit
promptinit
prompt agnoster

autoload zmv

export PATH=/usr/local/bin:~/bin:/usr/local/m-cli:$PATH

export SVN_EDITOR=vim
export EDITOR=vim
export VISUAL=vim
export LESS="-R"

# Use shared SSH keys for CVS authentification
export CVS_RSH=ssh
export EC2_HOME=~/ec2-api-tools-1.2-13740/

export EC2_PRIVATE_KEY=~/aws/pk-TE6RCGHJHRQB4QPDJKGVTSVOJEEFI4TI.pem
export EC2_CERT=~/aws/cert-TE6RCGHJHRQB4QPDJKGVTSVOJEEFI4TI.pem

export LC_CTYPE=en_US.UTF-8

# Aliases
alias s="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias pw="openssl rand -base64 18 |md5 |head -c18;echo"
alias ll='ls -Fals'
#alias d=dotcloud
alias h=heroku
alias dco=docker-compose
alias chrome-no-web-security="open -a Google\ Chrome --args --disable-web-security --user-data-dir"

# Ruby rvm
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# virtualenvwrapper
export WORKON_HOME=~/virtual_envs
export PROJECT_HOME=~/git
# the next two lines are a hack to fix python 3 version
#export VIRTUALENVWRAPPER_LOG_DIR="$WORKON_HOME"
#export VIRTUALENVWRAPPER_HOOK_DIR="$WORKON_HOME"
source /Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenvwrapper.sh
#source /Library/Frameworks/Python.framework/Versions/3.5/bin/virtualenvwrapper.sh

# Haskell
export PATH="$HOME/Library/Haskell/bin:$PATH"

# Node Version Manager
export NVM_DIR=~/.nvm
#echo $(brew --prefix nvm)/nvm.sh --no-use
source $(brew --prefix nvm)/nvm.sh --no-use

test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
# Hook for desk activation
[ -n "$DESK_ENV" ] && source "$DESK_ENV" || true
